### ISSUE TITLE
Write a matrix.

### ISSUE THREAD

**Issue by garlofrank** [mathquill/mathquill#332]
Can you write matrices with mathquill? I thought it was not possible, but then I saw this page, and some others.

http://www.mathjq.com/

I tried to write an array with this command, but this does not work
$('...').mathquill('write', '\begin{matrix}{}&{}\{}&{}\end{matrix}');

I really do not know if it's possible or if the above link uses a modified version of mathquill.

Can anyone tell me if it is possible ?.

Sorry, I forgot to say hello.
I spend all day working with this and I'm tired.
Hi everyone.

**Comment by dwendt** [comment]
If the branch is solid, why not merge it into master? Matrices are very common...

**Comment by Gregoor** [comment]
+1

**Comment by w0pke** [comment]
+1

**Comment by eoghanmcilwaine** [comment]
Just to keep this updated... I created a [matrix branch on our fork](https://github.com/Learnosity/mathquill/tree/matrix) which is (currently) up to date with the latest mathquill/dev. Best to use this instead of the commit I posted in my last comment.

To @dwendt and +1ers; merging into master is probably an issue for @laughinghan et al. But I can understand why there might be reluctance to add 500+ lines of code for just this one feature. I'm quite interested in the project owners' thoughts on this actually. I'd be happy to listen to feedback and make substantial changes if there's a prospect of getting this merged.

**Comment by laughinghan** [comment]
@eoghanmcilwaine: my thoughts are that your code looks like a great, well-written, useful hack, but one big aim I have on the `dev` branch is to reduce divergence from "canonical" LaTeX (to the extent that exists...), and adding `\matrix`, `\pmatrix` etc commands would be moving in the opposite direction.

If you're able to parse `\begin{matrix}...\end{matrix}` without parsing anything that isn't currently valid LaTeX, and not export any invalid LaTeX, and (ideally) only export LaTeX that would also be able to be parsed by MathQuill, then I'd be delighted to merge it. (I'll probably also have lots of opinions about your interaction to create and edit and delete matrices, but that's so much easier to change later, so I'd be much more amenable to just shipping it and improving it later.)

If MathQuill's current parser system is getting in the way of that, I'd say the "right" thing to do is to properly fix that rather than add more easy-to-parse invalid LaTeX. My dissatisfactions with the parser system have been gradually accumulating&mdash;performance and complexity for one, but also, I'd love to be able to parse the old infix(-ish) Plain TeX commands like `{1 \over 2}`, `{n \choose k}`, `{\root 3 \of 2}` etc (LaTeX provides prefix commands as alternatives: `\frac{1}{2}`, `\binom{n}{k}`, `\sqrt[3]{2}`, respectively; I'm unclear on why, it didn't simplify parsing for anybody, everybody ends up having to [support both](http://mathb.in/37486), plus parsing rules for the square bracket "optional block" delimiters are idiosyncratic).

**Comment by laughinghan** [comment]
Just to add a little warmth: everyone, thanks for your interest in MathQuill, I'm excited just knowing people care enough to comment on these issues! :smile:

Matrices would be awesome, @eoghanmcilwaine's work is excellent, I just have some compatibility concerns, as described.

**Comment by eoghanmcilwaine** [comment]
Thanks for the feedback @laughinghan, good points there.

I see what you mean about `\matrix`, `\pmatrix` etc, and the parser issues that go along with that. If I can fix this cleanly without mangling the parser I will try to get a pull request ready. (Actually, speaking of parser issues, have you noticed that you can manually input deeply nested content, but then get a "Maximum call stack size exceeded" error parsing the same content when initializing or pasting?)

Mathquill is really quite awesome, and it's a pleasure to be able to contribute. :smile:

**Comment by d4l3k** [comment]
Thanks for all your work. I'd love to see this merged in.

I'm trying to use @eoghanmcilwaine's matrix fork https://github.com/Learnosity/mathquill/tree/matrix, but it's throwing an error when using the compiled version.

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
(anonymous function) @ VM8651:2339
C.open @ VM8651:179P @ VM8651:202
(anonymous function) @ VM8651:2266
(anonymous function) @ VM8651:5137
jQuery.extend.globalEval @ jquery.js?body=1:329
jQuery.ajaxSetup.converters.text script @ jquery.js?body=1:8662
ajaxConvert @ jquery.js?body=1:7797
done @ jquery.js?body=1:8216
jQuery.ajaxTransport.options.send.callback @ jquery.js?body=1:8606
jQuery.ajaxTransport.options.send @ jquery.js?body=1:8631
jQuery.extend.ajax @ jquery.js?body=1:8167
jQuery._evalUrl @ jquery.js?body=1:8324
jQuery.fn.extend.domManip @ jquery.js?body=1:5433
jQuery.fn.extend.append @ jquery.js?body=1:5219
(anonymous function) @ equations.js:8
context.execCb @ require.js?body=1:1679
Module.check @ require.js?body=1:879
Module.enable @ require.js?body=1:1166
Module.init @ require.js?body=1:784
callGetModule @ require.js?body=1:1193
context.completeLoad @ require.js?body=1:1572
context.onScriptLoad @ require.js?body=1:1700
``` 

Seems to be happening under `TextBlock`
```
  _.selectTowards = MathCommand.prototype.selectTowards;
```

**Comment by eoghanmcilwaine** [comment]
Hey @d4l3k, I just updated the branch with a [very basic matrix test page](https://github.com/Learnosity/mathquill/blob/matrix/test/matrix.html) and [build instructions](https://github.com/Learnosity/mathquill/wiki/Building-and-testing-matrix). This runs without any error. If you're still having trouble, send me some more info (e.g. browser, matrix latex) and I'll see if I can reproduce the issue.

**Comment by d4l3k** [comment]
I'm still getting issues.
I've compiled a copy and launched it at http://nicki.fn.lc:8080/test/matrix.html

I'm using Chrome on ChromeOS. It seems like MathCommand is being used before it's declared.

Maybe it's something to do with my compilation setup?

### Chrome Details
Google Chrome	45.0.2454.86 (Official Build) (64-bit)
Revision	c9cfd5572d17dddaaef69cd6e45ebd76750a2150
Platform	7262.52.0 (Official Build) stable-channel swanky
Blink	537.36 (@201276)
JavaScript	V8 4.5.103.29
Flash	18.0.0.233-r1
User Agent	Mozilla/5.0 (X11; CrOS x86_64 7262.52.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.86 Safari/537.36

**Comment by d4l3k** [comment]
I've figured out the issue, but I'm not sure what's causing it.
```
cat src/intro.js node_modules/pjs/src/p.js src/tree.js src/cursor.js src/controller.js src/publicapi.js src/services/saneKeyboardEvents.util.js src/services/parser.util.js src/services/focusBlur.js src/services/exportText.js src/services/mouse.js src/services/keystroke.js src/services/textarea.js src/services/latex.js src/services/scrollHoriz.js src/commands/text.js src/commands/math.js src/commands/math/LatexCommandInput.js src/commands/math/commands.js src/commands/math/advancedSymbols.js src/commands/math/basicSymbols.js src/outro.js build/.exists--used_by_Makefile | ./script/escape-non-ascii > build/mathquill.js
```

When it cats the sources files together `src/commands/text.js` is before `src/commands/math.js`. This causes the variables to initialize out of order.

This might be caused by the filesystem being ext2. Renaming `text.js` to `z-text.js` works for some reason.

**Comment by laughinghan** [comment]
Crap, you might be experiencing #435

**Comment by eoghanmcilwaine** [comment]
Interesting. I did notice recently that the concat order is different on mac and linux, but assumed it didn't matter. We use both, so it's good to know about this error, thanks!

**Comment by hermanbergwerf** [comment]
I successfully tried the matrix fork from @eoghanmcilwaine on my machine. It can parse `\begin{matrix}...` but you cannot input that into the editor. I would really like to see matrices as they provide a nice way to write vectors.

**Comment by eoghanmcilwaine** [comment]
Hi @hermanbergwerf you can enter a matrix via direct keyboard input by typing "\bmatrix" etc. (not valid latex, just a shorthand).

If you want something a bit more specific to your implementation you could write your own key event listener and add the matrix via the mathquill API like this:
```
mathField.latex('\\begin{bmatrix}x\\end{bmatrix}');
```

Or you could hack mathquill's keystroke handler and add something [here](https://github.com/mathquill/mathquill/blob/560c055dcf3320a3ef3ed879d87408ba8824a58c/src/services/keystroke.js#L131) like:
```
case 'Shift-M':
      (Environments.bmatrix()).createLeftOf(cursor);
      break;
```

**Comment by hermanbergwerf** [comment]
@eoghanmcilwaine sure, but I mean it can probably not be merged into MathQuill as long as it supports any kind of non-standard syntax such as `\matrix`, which I indeed tried.

**Comment by alexf101** [comment]
@eoghanmcilwaine Thank you for your contributions, I ended up forking from your matrix branch as this issue seems to have gone stale.

In the interests of reusability I'd love to be able to pull request a couple of contributions back, but I'm a little confused about where the most matrixy MathQuill is supposed to live now? I ended up forking from the branch called [matrix](https://github.com/Learnosity/mathquill/tree/matrix) in Learnosity, but I'm not sure if that was the most up-to-date.

The things I added were:
- support in matrices for `leftRightIntoCmdGoes: 'up'`. If that config option is set, the left/right arrows move across the top of the matrix instead of looping through the entire thing. I haven't bothered implementing support for 'down', but I will if there's community interest.
- `align*` environment for rendering equations with aligned equals signs compatible with amsmath, modeled as a two-column matrix with a static middle column of equal signs.

There's still some bugs I'm trying to iron out, and I'll admit I'm a bit confused about MathQuill's data model. I'm reluctant to post a link to my code here (though I daresay a Github search would find it!) as I don't want to fork the community even further. So I guess I'm asking for a status update - is there still interest in merging matrix support into mathquill/mathquill so we can be good citizens and send pull requests somewhere central?

@laughinghan Is the main concern still compatibility of the `\matrix` command as opposed to `\begin{matrix}\end{matrix}`? I think I agree that it's not necessary for that to be included in core MathQuill - maintaining a small fork to support custom parsing features isn't super burdensome, especially compared to maintaining a whole different command suite. Is there anything I can do to help?

**Comment by eoghanmcilwaine** [comment]
@alexf101 as far as I'm aware our [Learnosity/mathquill:matrix](https://github.com/Learnosity/mathquill/tree/matrix) branch is the most complete matrix implementation so far - although yeah, it could do with a rebase to keep it up to date 😄  I'd love to take a look at your `leftRightIntoCmdGoes` contribution if you feel like making a pull request back to that branch?

Regarding the `align*` stuff: does that extend matrix? Or does it just rely on the [environment support](https://github.com/Learnosity/mathquill/blob/75376674e138768ecf228956f4dcbac5785fd97b/src/commands/math/commands.js#L810-L841) in our matrix branch?

**Comment by alexf101** [comment]
@eoghanmcilwaine The commit for leftRightIntoCmdGoes == 'up' support is https://github.com/StileEducation/mathquill/commit/5c3aa35450c6c26a4c953e6b01a1c04480d627ff.  I think we'd be better off attempting a cherry-pick than a pull request unless there's a way to ignore the difference in the branch bases - we're actually based off of Desmos's fork to get their improvements to accessibility.

In the interest of having a central place for discussion and improvement of MathQuill instead of a bunch of different forks for different features, I'd love to help get your work merged upstream, assuming @laughinghan is still interested. The issue is still just '\matrix', right? AFAICT that's already been removed from https://github.com/Learnosity/mathquill/tree/matrix or was never in that particular branch, so to be honest I'm a little confused as to what the blocker is. 

If there's actually no blocker anymore, I'd be happy to draft a PR to merge https://github.com/Learnosity/mathquill/tree/matrix upstream.

**Comment by eoghanmcilwaine** [comment]
@alexf101 I just rebased my matrix branch so it's now up to date with mathquill:master.

There are a few blockers related to the UI that we need to work through. I'll post here again when there's more news.

I don't think there's a remaining issue with invalid latex like `\matrix`. It's not supported by the parser, and shouldn't be. However we do allow it to be directly typed in to mathquill in LatexCommandInput mode. (Otherwise there'd be no way to create a matrix other than typing out `\begin{matrix}...` somewhere else and pasting it in to mathquill). We also support `\matrix` via the `cmd` public method. This doesn't imply that we're treating it as valid latex - we just fall back to checking environment names if the expression after the backslash wasn't recognised as a latex command.  I discussed this with @laughinghan and I believe he's on board.

**Comment by eoghanmcilwaine** [comment]
Thanks so much @alexf101! I'll give that a review.

**Comment by pansitwattana** [comment]
Waiting for this to be merged

**Comment by ultrainstinct1987** [comment]
> Saludos @garlofrank,
> 
> Last time I checked, matrices weren't available in core mathquill. But a few of us have added matrix support ourselves. Have a look at [this commit on my fork of mathquill/dev](https://github.com/Learnosity/mathquill/commit/50315cf9056946fd59f2ffc14e2b1d0e03f6ec4b) - it might be helpful.
> 
> Good luck, Eoghan

I am having issues compiling your version to support mathquill to support matrices. 
I run npm install and meet with the following error
npm ERR! code 1
npm ERR! path C:\Users\Andy\Documents\GitHub\mathquill\node_modules\pjs
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c make commonjs    
npm ERR! 'make' is not recognized as an internal or external command,  
npm ERR! operable program or batch file.

Can anyone help?

**Comment by jaltekruse** [comment]
@ultrainstinct1987  "'make' is not recognized as an internal or external command," - you need to install make in your environment, its a bit atypical compared to many javascript projects, but the build is driven by make not just npm.

**Comment by ultrainstinct1987** [comment]
> @ultrainstinct1987 "'make' is not recognized as an internal or external command," - you need to install make in your environment, its a bit atypical compared to many javascript projects, but the build is driven by make not just npm.

I fixed it. but it come with this error. i google it and i cannot install cat commands in cmd. 
Is there any other ways to do it?

**Comment by jaltekruse** [comment]
@ultrainstinct1987 I haven't tried building mathhquill in a Windows environment myself. You could try using the Windows subsystem for Linux (which despite the confusing name is about running programs in a Linux-like environment inside of windows).

https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by ultrainstinct1987** [comment]
> 

I manage to build it but the bracket aren’t displayed properly. Is it what it meant to be?

**Comment by jaltekruse** [comment]
There are different variants of matrix for different brackets
```
\begin{bmatrix}&\\&\end{bmatrix}
\begin{pmatrix}&\\&\end{pmatrix}
\begin{Bmatrix}&\\&\end{Bmatrix}
\begin{vmatrix}&\\&\end{vmatrix}
\begin{Vmatrix}&\\&\end{Vmatrix}
\begin{matrix}&\\&\end{matrix}
```

**Comment by ultrainstinct1987** [comment]
Yes. I mean the bracket does not cover all the number. It appear as a small { or [

**Comment by jaltekruse** [comment]
@ultrainstinct1987 hmm, that I'm not sure about, the learnosity code works for me.

This is my site with the matrix stuff working: https://freemathapp.org

Here is my mathquill fork I use in the site: https://github.com/jaltekruse/mathquill/commits/freemath_fork

**Comment by ultrainstinct1987** [comment]
> @ultrainstinct1987 hmm, that I'm not sure about, the learnosity code works for me.
> 
> This is my site with the matrix stuff working: https://freemathapp.org
> 
> Here is my mathquill fork I use in the site: https://github.com/jaltekruse/mathquill/commits/freemath_fork

I saw your website. It was nicely implemented. Could I contact you?

**Comment by jaltekruse** [comment]
@ultrainstinct1987 Sure, you can email me at hello@freemathapp.org

**Comment by ultrainstinct1987** [comment]
> @ultrainstinct1987 Sure, you can email me at [hello@freemathapp.org](mailto:hello@freemathapp.org)

Sure. I have send an email to you

**Comment by ultrainstinct1987** [comment]
How do you control the matrix after \matrix commands?
