### ISSUE TITLE
Changes in Mathquill Text box does not reflect until we press backspace aur right arrowkey + space

### ISSUE THREAD

**Issue by sharmatapan** [mathquill/mathquill#994]
I have created a math editor using mathquill where I have give a button to enter the text which inserts \\text{T} latex to input box and mathquill reflects a T with a border:
![1](https://user-images.githubusercontent.com/94465847/201329568-a14ce845-c52e-46ab-a703-2c0567bfbcdd.png)
Now to edit that text, use left key and enter the box and make changes but you will those changes are not reflected in the input field since the MQ.mathfield edit handler did not run
![2](https://user-images.githubusercontent.com/94465847/201329593-f0a82705-fb28-43c4-b49e-1fe1e59ca642.png)
And you will see only field getting updated when you press backspace aur right arrowkey + space
![3](https://user-images.githubusercontent.com/94465847/201329908-181d715b-83fd-41fe-a9fb-65cd1627d92e.png)

**Comment by jaltekruse** [comment]
@sharmatapan are you using mathquill from one of the release or a build of the master branch? I think this might have been addressed as I was seeing a similar issue in my use case of mathquill and @laughinghan made some fixes for text inputs in this changeset - https://github.com/mathquill/mathquill/pull/895

**Comment by sharmatapan** [comment]
Hello @jaltekruse, yup it seems the same issue. I tried the latest build from  https://www.npmjs.com/package/mathquill but issue persist. Can you please help

**Comment by sharmatapan** [comment]
Hello @jaltekruse , I created a build from master and tried using it but still see the same issue.

**Comment by sharmatapan** [comment]
@jaltekruse , I am using .latex() method in edit handler  to get the updated latex but until I click backspace or right arrowkey + space, update in text are not reflected in my state, infact edit handler is not run at all.
